import Link from "next/link";
import { AdminNav } from "@/components/admin/admin-nav";
import { StatCard } from "@/components/admin/stat-card";
import { requireAdminSession } from "@/lib/admin/auth";
import { aggregateAnalytics, flattenPapers, getAnalyticsEvents, getPapersData } from "@/lib/admin/storage";
export const dynamic = "force-dynamic";
export default function AdminDashboardPage() {
  const session = requireAdminSession(); const data = getPapersData(); const papers = flattenPapers(data); const metrics = aggregateAnalytics(getAnalyticsEvents()); const released = papers.filter((paper) => paper.status === "released").length; const withPdf = papers.filter((paper) => paper.pdf).length; const missingDescription = papers.filter((paper) => !paper.summary).slice(0, 8); const releasedMissingDoi = papers.filter((paper) => paper.status === "released" && !paper.doi).slice(0, 8);
  return <div><AdminNav username={session.username} /><main className="mx-auto max-w-6xl px-4 py-10"><div className="flex items-start justify-between gap-3 md:gap-6 flex-wrap"><div><p className="text-xs uppercase tracking-[0.2em] text-black/55">Admin dashboard</p><h1 className="mt-3 text-3xl font-semibold tracking-tight">Corpus control room</h1><p className="mt-3 max-w-3xl text-sm text-black/65 leading-relaxed">Manage public paper metadata, PDF replacements, download tracking, and site-level reading statistics.</p></div><Link href="/admin/papers/new" className="no-underline rounded-2xl bg-black px-5 py-3 text-sm font-medium text-white hover:bg-black/90">Add paper</Link></div><section className="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-4"><StatCard label="Corpus entries" value={papers.length} help="Includes executive summary and all paper records." /><StatCard label="Released" value={released} help="Public status marked Released." /><StatCard label="PDF-linked" value={withPdf} help="Entries with a PDF path." /><StatCard label="Downloads tracked" value={metrics.downloads} help="Counts clicks through tracked download links." /></section><section className="mt-8 grid gap-3 md:gap-6 lg:grid-cols-2"><div className="rounded-2xl border border-black/10 bg-white/70 p-6"><h2 className="text-lg font-semibold">Reader activity</h2><div className="mt-5 grid gap-3 sm:grid-cols-3"><StatCard label="24 hours" value={metrics.last24h} /><StatCard label="7 days" value={metrics.last7d} /><StatCard label="30 days" value={metrics.last30d} /></div><Link href="/admin/statistics" className="mt-5 inline-flex no-underline text-sm text-black/70 hover:text-black">Open statistics →</Link></div><div className="rounded-2xl border border-black/10 bg-white/70 p-6"><h2 className="text-lg font-semibold">Attention needed</h2><div className="mt-4 space-y-4 text-sm"><div><p className="font-medium">Released without DOI</p>{releasedMissingDoi.length ? <ul className="mt-2 space-y-1 text-black/60">{releasedMissingDoi.map((paper) => <li key={paper.slug}>{paper.title}</li>)}</ul> : <p className="mt-2 text-black/50">None found.</p>}</div><div><p className="font-medium">Missing short description</p>{missingDescription.length ? <ul className="mt-2 space-y-1 text-black/60">{missingDescription.map((paper) => <li key={paper.slug}>{paper.title}</li>)}</ul> : <p className="mt-2 text-black/50">None found.</p>}</div></div></div></section><section className="mt-8 rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm text-amber-950 leading-relaxed"><p className="font-medium">Deployment note</p><p className="mt-1">This admin layer writes to content/papers.json, public/papers, and data/*.jsonl on the server filesystem. That is ideal for local/self-hosted operation and staging. On read-only or ephemeral serverless hosts, connect these functions to durable storage before relying on runtime edits.</p></section></main></div>;
}
