// app/deep/purpose/formal/page.tsx
import type { Metadata } from "next";
import Link from "next/link";
import { Button } from "@/components/ui/button";

export const metadata: Metadata = {
  title: "Purpose (P) – Technical notes | Informational Ontology",
  description:
    "Formal treatment of Purpose (P) as temporally extended, value-structured trajectories in Informational Ontology.",
};

export default function FormalPurposePage() {
  return (
    <main className="mx-auto max-w-5xl px-4 py-12 space-y-10">
      {/* Header */}
      <section className="space-y-3">
        <p className="text-sm font-semibold tracking-wide text-sky-400">
          Technical notes · Purpose (P)
        </p>
        <h1 className="text-2xl font-semibold tracking-tight text-slate-50">
          P as Teleodynamic Structure
        </h1>
        <p className="text-sm text-slate-300">
          This page formalizes Purpose (P) as meaning extended through time:
          structured trajectories of action through state space, guided by
          stable value and meaning structures. Teleology is treated here not as
          an external imposition but as an emergent property of systems that
          maintain and pursue high-value configurations.
        </p>
      </section>

      {/* Abstract */}
      <section className="space-y-3">
        <h2 className="text-lg font-semibold text-slate-50">Abstract</h2>
        <p className="text-sm text-slate-300">
          In Informational Ontology, purpose arises when value-laden meanings
          organize behavior over time. Given a state space S, a value function
          V, and a policy π that selects actions based on representations with
          meaning M, we can define purposes as attractors or preferred
          trajectories in S. This yields a non-mystical, non-anthropocentric
          notion of teleology: systems have purposes insofar as their dynamics
          reliably favor subsets of S given their informational structure.
        </p>
      </section>

      {/* 1. Policies and trajectories */}
      <section className="space-y-3">
        <h2 className="text-lg font-semibold text-slate-50">
          1. Policies and Trajectories
        </h2>
        <p className="text-sm text-slate-300">
          Let S be a Δ-structured state space, A a set of actions, and P(s&apos; |
          s, a) transition probabilities. A <span className="italic">policy</span>{" "}
          is a function:
        </p>
        <p className="font-mono text-xs text-slate-300">
          π: S → A
        </p>
        <p className="text-sm text-slate-300">
          specifying which action an agent tends to take in each state. A
          trajectory is a sequence (s<sub>0</sub>, s<sub>1</sub>, s<sub>2</sub>,
          …) generated by repeatedly applying π and P.
        </p>
      </section>

      {/* 2. Purpose as preferred sets / attractors */}
      <section className="space-y-3">
        <h2 className="text-lg font-semibold text-slate-50">
          2. Purpose as Preferred Regions and Attractors
        </h2>
        <p className="text-sm text-slate-300">
          Suppose we have a value function V: S → ℝ and a policy π that tends
          to increase expected value. Let S<sub>*</sub> be a subset of S such
          that:
        </p>
        <p className="font-mono text-xs text-slate-300">
          lim<sub>t→∞</sub> P(s<sub>t</sub> ∈ S<sub>*</sub> | s<sub>0</sub>) →
          1
        </p>
        <p className="text-sm text-slate-300">
          for a wide range of starting states s<sub>0</sub>. Then S<sub>*</sub>{" "}
          is an attractor region under the value-guided dynamics.
        </p>
        <p className="text-sm text-slate-300">
          <span className="font-semibold">Definition 1.</span> A{" "}
          <span className="italic">purpose</span> (in IO&apos;s technical sense)
          is an attractor region S<sub>*</sub> in S, together with a policy π
          and value function V, such that trajectories under π systematically
          converge on S<sub>*</sub> because of its high value.
        </p>
        <p className="text-sm text-slate-300">
          Intuitively, the system &quot;has the purpose&quot; of being in or
          maintaining S<sub>*</sub>.
        </p>
      </section>

      {/* 3. Representation and explicit goals */}
      <section className="space-y-3">
        <h2 className="text-lg font-semibold text-slate-50">
          3. Goals as Represented Purposes
        </h2>
        <p className="text-sm text-slate-300">
          When a system not only behaves in ways that converge on S<sub>*</sub>
          but also represents S<sub>*</sub> in its internal model Σ and
          associates high meaning M*(σ) with those representations, we move
          from implicit to explicit purpose.
        </p>
        <p className="text-sm text-slate-300">
          <span className="font-semibold">Definition 2.</span> A{" "}
          <span className="italic">goal</span> is a purpose S<sub>*</sub>{" "}
          together with a subset Σ<sub>*</sub> ⊆ Σ such that:
        </p>
        <ul className="list-disc space-y-1 pl-5 text-sm text-slate-300">
          <li>
            σ(σ) ∈ S<sub>*</sub> for σ ∈ Σ<sub>*</sub>, and
          </li>
          <li>
            M*(σ) is among the highest in the system&apos;s representational
            repertoire.
          </li>
        </ul>
        <p className="text-sm text-slate-300">
          Now the system not only tends toward S<sub>*</sub>, but &quot;knows
          what it is doing&quot; in the limited, structural sense of carrying
          internal states that stand for and favor S<sub>*</sub>.
        </p>
      </section>

      {/* 4. Teleology without external design */}
      <section className="space-y-3">
        <h2 className="text-lg font-semibold text-slate-50">
          4. Teleology Without External Design
        </h2>
        <p className="text-sm text-slate-300">
          This formalization allows IO to speak of purpose and teleology
          without positing an external designer or intrinsic &quot;oughts&quot;
          beyond the system&apos;s own structure. Teleology is simply:
        </p>
        <ul className="list-disc space-y-1 pl-5 text-sm text-slate-300">
          <li>
            value functions V shaped by evolutionary, learning, or design
            processes,
          </li>
          <li>
            policies π that apply representational meanings M to choose actions,
          </li>
          <li>
            resulting trajectories that reliably approach certain regions of S.
          </li>
        </ul>
        <p className="text-sm text-slate-300">
          Purpose, on this view, is a structural feature of dynamical systems
          embedded in informational environments, not a metaphysical extra.
        </p>
      </section>

      {/* 5. Ethical and practical implications (pointer) */}
      <section className="space-y-3">
        <h2 className="text-lg font-semibold text-slate-50">
          5. Toward Ethics and Practice
        </h2>
        <p className="text-sm text-slate-300">
          The ethical sections of IO take these formal notions of value and
          purpose and scale them to multi-agent systems, societies, and
          long-term trajectories. System-stability ethics, informational
          flourishing, and alignment all presuppose the technical notion of
          purpose developed here.
        </p>
        <p className="text-sm text-slate-300">
          Those topics are treated in the later sections of the Rev4 master and
          in simulation modules, rather than in this deep-dive chain itself.
        </p>
      </section>

      {/* Back link */}
      <section className="border-t border-slate-800 pt-6">
        <Link href="/deep/purpose">
          <Button variant="outline" className="border-slate-700">
            ← Back to Purpose deep dive
          </Button>
        </Link>
      </section>
    </main>
  );
}
