import Link from "next/link";
import { AdminNav } from "@/components/admin/admin-nav";
import { requireAdminSession } from "@/lib/admin/auth";
import { getPapersData } from "@/lib/admin/storage";
export const dynamic = "force-dynamic";
export default function AdminPapersPage() {
  const session = requireAdminSession(); const data = getPapersData();
  return <div><AdminNav username={session.username} /><main className="mx-auto max-w-6xl px-4 py-10"><div className="flex items-start justify-between gap-6 flex-wrap"><div><p className="text-xs uppercase tracking-[0.2em] text-black/55">Admin</p><h1 className="mt-3 text-3xl font-semibold tracking-tight">Paper manager</h1><p className="mt-3 text-sm text-black/60">Edit metadata, status, DOI links, and PDFs.</p></div><Link href="/admin/papers/new" className="no-underline rounded-2xl bg-black px-5 py-3 text-sm font-medium text-white hover:bg-black/90">Add paper</Link></div>{data.executive_summary ? <section className="mt-8 rounded-2xl border border-black/10 bg-white/70 p-5"><div className="flex items-start justify-between gap-6 flex-wrap"><div><p className="text-xs uppercase tracking-[0.16em] text-black/45">Orientation document</p><h2 className="mt-1 font-semibold">{data.executive_summary.title}</h2><p className="mt-1 text-sm text-black/55">{data.executive_summary.status}</p></div><Link href={`/admin/papers/${data.executive_summary.slug}`} className="no-underline rounded-2xl border border-black/10 bg-white px-4 py-2 text-sm text-black/70 hover:bg-black/5">Edit</Link></div></section> : null}<div className="mt-8 space-y-8">{data.groups.map((group) => <section key={group.id}><div className="flex items-baseline justify-between gap-4 flex-wrap"><h2 className="text-xl font-semibold">{group.title}</h2><span className="text-xs text-black/45">{group.items.length} entries</span></div><div className="mt-4 divide-y divide-black/10 overflow-hidden rounded-2xl border border-black/10 bg-white/70">{group.items.map((paper) => <div key={paper.slug} className="p-5 flex items-start justify-between gap-6 flex-wrap"><div className="min-w-[18rem]"><div className="flex items-center gap-2 text-xs text-black/45 flex-wrap"><span>Internal no. {paper.paper_no ?? "—"}</span><span>•</span><span>{paper.status}</span>{paper.state ? <><span>•</span><span>{paper.state}</span></> : null}</div><h3 className="mt-1 font-medium">{paper.title}</h3><p className="mt-1 text-xs text-black/45">/{paper.slug}</p>{paper.pdf ? <p className="mt-1 text-xs text-black/45">PDF: {paper.pdf}</p> : null}</div><div className="flex gap-2"><Link href={`/papers/${paper.slug}`} className="no-underline rounded-2xl border border-black/10 bg-white px-4 py-2 text-sm text-black/70 hover:bg-black/5">Public page</Link><Link href={`/admin/papers/${paper.slug}`} className="no-underline rounded-2xl border border-black/10 bg-white px-4 py-2 text-sm text-black/70 hover:bg-black/5">Edit</Link></div></div>)}</div></section>)}</div></main></div>;
}
