// app/deep/information/formal/page.tsx
import type { Metadata } from "next";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { ExplanatoryBanner } from "@/components/ExplanatoryBanner";

export const metadata: Metadata = {
  title: "Information (I) — Formal layer | Informational Ontology",
  description: "How Relation (R) generates Information (I), and what it means for information to exist (Rev 5).",
};

export default function FormalPage() {
  return (
    <main className="mx-auto max-w-5xl px-4 py-12 space-y-10">
      <ExplanatoryBanner className="mb-8" />
      <section className="space-y-3">
        <p className="text-sm font-semibold tracking-wide text-sky-400">
          Formal layer · I — Information
        </p>
        <h1 className="text-3xl font-bold tracking-tight sm:text-4xl">
          Information (I)
        </h1>
        <p className="max-w-3xl text-sm text-slate-400 leading-relaxed">
          This page is a structured extract of the Rev 5 master text (Sections 4.4–4.5).
          It is intended as a precise anchor for the “Deep Dive” section, not as an expansion of the ontology.
        </p>
      </section>

      <section className="space-y-4">
        <p className="text-base text-slate-300 leading-relaxed">Relation alone is not yet information. For information to arise, relations must exhibit structure. When differences are related in a stable or patterned way, information comes into existence. Information, in the Informational Ontology, is defined as structured difference. This definition is ontological rather than epistemic. Information is not dependent on observers, interpretation, language, or meaning. It does not require minds, symbols, or semantic content.</p>
        <p className="text-base text-slate-300 leading-relaxed">Wherever differences are arranged in non-random, relational patterns, information exists. This definition distinguishes informational ontology from purely mathematical, computational, or communicative notions of information. While such frameworks may model or measure information, they do not exhaust its ontological scope. Information is not restricted to human knowledge, digital encoding, or Shannon-style signal transmission. Those are special cases of informational structures, not their source.</p>
        <p className="text-base text-slate-300 leading-relaxed">Information becomes structurally unavoidable when relations stabilize into re-identifiable patterns under ordering and selection. Once differences are related, those relations may persist, repeat, or stabilize. The moment relational patterns become distinguishable from mere flux, information is present. No additional ontological primitive is required beyond the structural commitments stated in Section 1. Thus, information is not imposed upon relations from the outside.</p>
        <p className="text-base text-slate-300 leading-relaxed">It is generated by relational structure itself. This transition—from relation to information—is denoted as R → I. It marks the emergence of structured existence from mere distinction. Information is not identical to relation. Information is present when relational differences stabilize into re-identifiable patterns under ordering. Relations may be transient, unstructured, or indistinguishable from flux; in such cases, informational structure is not yet established.</p>
        <p className="text-base text-slate-300 leading-relaxed">Under persistence and selection, however, patterned relations endure, and it is this endurance of structured difference that constitutes information in the ontological sense. 4.5 Information as the First Structured Mode of Being Information represents the first structured mode of existence. While difference establishes distinction and relation establishes comparison, information arises when relational differences stabilize into identifiable patterns. At this stage, existence acquires form.</p>
        <p className="text-base text-slate-300 leading-relaxed">Information enables persistence by allowing patterns to remain recognizable across change. It enables recursion by allowing informational structures to operate on or reference other informational structures. It enables feedback by allowing the effects of relations to influence future relations. It enables integration by allowing multiple differences to cohere into unified patterns. Without information, there can be no systems—only transient distinctions without continuity.</p>
        <p className="text-base text-slate-300 leading-relaxed">Information provides the substrate upon which systems emerge, endure, and interact. It is the minimal condition under which complexity becomes possible. Information is not yet meaning, value, or purpose. Those arise at later stages of the ontology. At this foundational level, information is simply structured difference, capable of being maintained, modified, and propagated.</p>
        <p className="text-base text-slate-300 leading-relaxed">Because information is the first structured ontological layer, all higher-order phenomena—physical systems, biological organization, cognitive processes, and social structures—must be expressible in informational terms. This does not reduce those phenomena to information in a trivial sense, but identifies information as the common structural substrate that makes them possible.</p>
        <p className="text-base text-slate-300 leading-relaxed">Information therefore occupies a pivotal position in the ontology: it is the bridge between mere distinction and the emergence of organized reality. Part V — Awareness</p>
      </section>

      <section className="rounded-2xl border border-slate-800 bg-slate-900/30 p-6 space-y-3">
        <h2 className="text-lg font-semibold">Navigation</h2>
        <div className="flex flex-wrap gap-3">
          <Link href="/deep/relation/formal">
            <Button variant="outline">← Previous</Button>
          </Link>
          <Link href="/deep">
            <Button variant="outline">Deep Dive index</Button>
          </Link>
          <Link href="/deep/awareness/formal">
            <Button>Next →</Button>
          </Link>
        </div>
      </section>
    </main>
  );
}